# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FITSKeywordPanel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FITSKWDialog(object):
    def setupUi(self, FITSKWDialog):
        FITSKWDialog.setObjectName("FITSKWDialog")
        FITSKWDialog.resize(710, 502)
        FITSKWDialog.setSizeGripEnabled(True)
        FITSKWDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(FITSKWDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(FITSKWDialog)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 0, 1, 1)
        self.fitskw_dialogbutts = QtWidgets.QDialogButtonBox(self.widget_4)
        self.fitskw_dialogbutts.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.fitskw_dialogbutts.setObjectName("fitskw_dialogbutts")
        self.gridLayout_13.addWidget(self.fitskw_dialogbutts, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 24, 0, 1, 2)
        self.widget = QtWidgets.QWidget(FITSKWDialog)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fitskw_hdu = QtWidgets.QSpinBox(self.widget)
        self.fitskw_hdu.setAlignment(QtCore.Qt.AlignCenter)
        self.fitskw_hdu.setSuffix("")
        self.fitskw_hdu.setObjectName("fitskw_hdu")
        self.gridLayout_3.addWidget(self.fitskw_hdu, 0, 2, 1, 1)
        self.fitskw_remove = QtWidgets.QPushButton(self.widget)
        self.fitskw_remove.setObjectName("fitskw_remove")
        self.gridLayout_3.addWidget(self.fitskw_remove, 3, 0, 1, 3)
        self.fitskw_loadlist = QtWidgets.QPushButton(self.widget)
        self.fitskw_loadlist.setObjectName("fitskw_loadlist")
        self.gridLayout_3.addWidget(self.fitskw_loadlist, 6, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.txt_hduchooser = QtWidgets.QLabel(self.widget)
        self.txt_hduchooser.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_hduchooser.setObjectName("txt_hduchooser")
        self.gridLayout_3.addWidget(self.txt_hduchooser, 0, 0, 1, 2)
        self.fitskw_add = QtWidgets.QPushButton(self.widget)
        self.fitskw_add.setDefault(False)
        self.fitskw_add.setObjectName("fitskw_add")
        self.gridLayout_3.addWidget(self.fitskw_add, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)
        self.txt_fitskw_status = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.txt_fitskw_status.setFont(font)
        self.txt_fitskw_status.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fitskw_status.setObjectName("txt_fitskw_status")
        self.gridLayout_3.addWidget(self.txt_fitskw_status, 7, 0, 1, 1)
        self.fitskw_savelist = QtWidgets.QPushButton(self.widget)
        self.fitskw_savelist.setObjectName("fitskw_savelist")
        self.gridLayout_3.addWidget(self.fitskw_savelist, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.fitskw_listing = QtWidgets.QListWidget(FITSKWDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fitskw_listing.setFont(font)
        self.fitskw_listing.setDragEnabled(True)
        self.fitskw_listing.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.fitskw_listing.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.fitskw_listing.setSelectionRectVisible(True)
        self.fitskw_listing.setObjectName("fitskw_listing")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fitskw_listing.addItem(item)
        self.gridLayout.addWidget(self.fitskw_listing, 1, 0, 3, 1)
        self.txt_fitskw_hint = QtWidgets.QLabel(FITSKWDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.txt_fitskw_hint.setFont(font)
        self.txt_fitskw_hint.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fitskw_hint.setObjectName("txt_fitskw_hint")
        self.gridLayout.addWidget(self.txt_fitskw_hint, 4, 0, 1, 1)

        self.retranslateUi(FITSKWDialog)
        QtCore.QMetaObject.connectSlotsByName(FITSKWDialog)

    def retranslateUi(self, FITSKWDialog):
        _translate = QtCore.QCoreApplication.translate
        FITSKWDialog.setWindowTitle(_translate("FITSKWDialog", "FITS Keyword and HDU Selector"))
        self.fitskw_remove.setText(_translate("FITSKWDialog", "Remove Keyword"))
        self.fitskw_loadlist.setText(_translate("FITSKWDialog", "Load List ..."))
        self.txt_hduchooser.setText(_translate("FITSKWDialog", "HDU to Search for Keywords (0 indexed)"))
        self.fitskw_add.setText(_translate("FITSKWDialog", "Add Keyword"))
        self.txt_fitskw_status.setText(_translate("FITSKWDialog", "No file loaded or saved ..."))
        self.fitskw_savelist.setText(_translate("FITSKWDialog", "Save List ..."))
        __sortingEnabled = self.fitskw_listing.isSortingEnabled()
        self.fitskw_listing.setSortingEnabled(False)
        item = self.fitskw_listing.item(0)
        item.setText(_translate("FITSKWDialog", "DATE-OBS"))
        item = self.fitskw_listing.item(1)
        item.setText(_translate("FITSKWDialog", "OBS_ID"))
        item = self.fitskw_listing.item(2)
        item.setText(_translate("FITSKWDialog", "SPECTEL1"))
        item = self.fitskw_listing.item(3)
        item.setText(_translate("FITSKWDialog", "SPECTEL2"))
        item = self.fitskw_listing.item(4)
        item.setText(_translate("FITSKWDialog", "MISSN-ID"))
        item = self.fitskw_listing.item(5)
        item.setText(_translate("FITSKWDialog", "DATASRC"))
        item = self.fitskw_listing.item(6)
        item.setText(_translate("FITSKWDialog", "INSTRUME"))
        self.fitskw_listing.setSortingEnabled(__sortingEnabled)
        self.txt_fitskw_hint.setText(_translate("FITSKWDialog", "Note: Drag and Drop Items to Reorder"))

